# Generated by Django 5.0.6 on 2024-07-03 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chat", "0002_brianbot_delete_chat"),
    ]

    operations = [
        migrations.RenameField(
            model_name="brianbot",
            old_name="messageinput",
            new_name="messageInput",
        ),
    ]
